language: R
R:
  - oldrel
  - release
  - devel
  
cache: packages

os:
  - linux
  - osx

install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then   choco install -y r --version 4.0.2.        ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then   choco install -y rtools --version=4.0.0    ; fi

warnings_are_errors: false
