language: R
R:
  - oldrel
  - release
  - devel
  
cache: packages

os:
  - linux
  - osx
    #disable_homebrew: true
  #- windows  # Windows appears to be currently unsuported in TravisCI


#matrix:
#  exclude:
#  Will need to exclude R-devel on MacOS
#  - os: osx
#    r: devel

matrix:
  include:
  # macOS
  ## OS: xcode7.3 - r oldrel
  - os: osx
    osx_image: xcode7.3
    disable_homebrew: true
  ## OS: xcode9.3 - r oldrel, release, devel
  - os: osx
    osx_image: xcode9.3
    disable_homebrew: true
    r: oldrel
  - os: osx
    osx_image: xcode9.3
    disable_homebrew: true
    r: release
  - os: osx
    osx_image: xcode9.3
    disable_homebrew: true
    r: devel
  ## OS: xcode12.2 - r oldrel
  - os: osx
    osx_image: xcode12.2
    fortran: false
  # linux
# linux OS already included above
#   - os: linux
#     r: release
#   - os: linux
#     r: devel
#     env: R_CODECOV=true

warnings_are_errors: false


# for codecov
r_packages:
  - covr
#  - knitr
#  - devtools
#  - knitr
#  - devtools
#  - roxygen2
#  - markdown
#  - testthat


##before_install:
##  #- R -e 'devtools::install_deps(dep = T)'
##  - Rscript -e "pckgs <- c('knitr', 'readxl', 'ape', 'rentrez', 'plotly', 'htmlwidgets', 'deSolve', 'gplots', 'pheatmap', 'shiny','shinydashboard','shinycssloaders','collapsibleTree','devtools','roxygen2','markdown','testhat'); install.packages(pckgs)"

# skip Travid-CI trigger builds for "daily updates" (which are reflected in files in "man/figures"
before_install:
 - |
   if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(man/figures)|(.txt)'
   then
     echo "Not running CI since only docs were changed."
     exit
   fi


#install:
#  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then   choco install -y r --version 4.0.2.        ; fi
#  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then   choco install -y rtools --version=4.0.0    ; fi



# only report coverage after build is successful
after_success:
  - Rscript -e 'covr::codecov()'


# emails
notifications:
  email:
    on_success: change
    on_failure: change
